const THROW_EXCEPTION = {
  UNKNOWN: 'Unknown error! Please try again later.',
};

export { THROW_EXCEPTION };
